config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
  get 'users/sign_out', to: 'users/sessions#destroy'
  end
  resources :calories
  get '/track', to: 'calories#track'
  resources :track_resets, only: [ :create ]
  get '/shared', to: 'track_resets#shared_progress'
  post '/goal', to: 'track_resets#update_goal'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
end

app/controllers/calories_controller.rb
class CaloriesController < ApplicationController
  before_action :user_signed_in?
  before_action :correct_user,   only: [ :destroy, :show, :edit ]
  def index
    @calories = current_user.calories.page(params[:page]).per(30)
  end

  def new
    @calorie = current_user.calories.build if user_signed_in?
  end

  def edit
    @calorie = current_user.calories.find(params[:id])
  end

  def create
    @calorie = current_user.calories.build(calorie_params)
    if @calorie.save
      flash[:success] = "Register created successfully!"
      redirect_to calories_path
    else
      render 'new'
    end
  end

  def update
    @calorie = current_user.calories.find(params[:id])
    if @calorie.update_attributes(calorie_params)
      flash[:success] = "Register updated correctly!"
      redirect_to @calorie
    else
      render 'edit'
    end
  end

  def show
    @calorie = current_user.calories.find(params[:id])
  end

  def destroy
    @calorie.destroy
    flash[:success] = "Register deleted"
    redirect_to request.referrer || calories_path
  end

  def track
  end

  private

    def calorie_params
      params.require(:calorie).permit(:number, :type_gained, :activity, :date)
    end

    def correct_user
      @calorie = current_user.calories.find_by(id: params[:id])
      redirect_to root_url if @calorie.nil?
    end

end

app/helpers/calories_helper.rb
module CaloriesHelper
  def calories_chart_data( start = 4.weeks.ago )
    gained_number_by_day = current_user.calories.where(type_gained: true).number_grouped_by_day(start)
    burned_number_by_day = current_user.calories.where(type_gained: false).number_grouped_by_day(start)
    (start.to_date..Date.today).map do |date|
      {
        date: date,
        gained_number: gained_number_by_day[date].try(:first).try(:total_calories) || 0,
        burned_number: burned_number_by_day[date].try(:first).try(:total_calories) || 0
      }
    end
  end

  def calories_chart_progress_data( start = 4.weeks.ago, user )
    gained_number_by_day = user.calories.where(type_gained: true).number_grouped_by_day(start)
    burned_number_by_day = user.calories.where(type_gained: false).number_grouped_by_day(start)
    (start.to_date..Date.today).map do |date|
      {
        date: date,
        gained_number: gained_number_by_day[date].try(:first).try(:total_calories) || 0,
        burned_number: burned_number_by_day[date].try(:first).try(:total_calories) || 0
      }
    end
  end
end

app/views/calories/_calorie.html.erb
<tr id="calorie-<%= calorie.id %>">
  <td class="activity"><%= calorie.activity %></td>
  <td class="type"><%= calorie.type_gained ? "Gained" : "Burned" %></td>
  <td class="date">
    Posted <%= time_ago_in_words(calorie.date) %> ago.
  </td>
  <td class="edit"><%= link_to "edit", edit_calorie_path(calorie.id) %>
    <% if current_user == calorie.user %>
     | <%= link_to "delete", calorie, method: :delete, data: { confirm: "You sure?" } %>
    <% end %>
  | <%= link_to "show", calorie %>
  </td>
</tr>

app/views/calories/_form.html.erb
<%= form_for @calorie do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :number, 'Number of calories', class: 'label' %>
    <div class="control">
      <%= f.number_field :number, class: 'input', step: 0.01, placeholder: 'Add a number of calories' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :type_gained, 'Type of calories', class: 'label' %>
    <div class="control">
      <div class="select">
        <%= f.select :type_gained, [['Gained', true], ['Burned', false]], class: 'select' %>
      </div>
    </div>
  </div>
  
  <div class="field">
    <%= f.label :activity, class: 'label' %>
    <div class="control">
      <%= f.text_field :activity, class: 'textarea', placeholder: 'Which activity did you realize?', value: 'Not specified' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :date, class: 'label' %>
    <div class="control">
      <%= f.datetime_field :date %>
    </div>
  </div>

  <%= f.submit yield(:button_text), class: "button is-link" %>
<% end %>

app/views/calories/edit.html.erb
<% provide(:title, 'Update register') %>
<% provide(:button_text, 'Update register') %>

<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= "Edit this register of calories" %>
      </h1>
      <h2 class="subtitle">
        <%= "#{current_user.email}" %>
      </h2>
      <h3>
        <%= yield(:date) %>
      </h3>
      <div class="columns">
        <div class="column is-two-fifths">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/calories/index.html.erb
<% provide(:title, 'All calories') %>
<% provide(:date, Time.now.to_s(:long)) %>

<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= "All registers of" %>
      </h1>
      <h2 class="subtitle">
        <%= "#{current_user.email}" %>
      </h2>
      <h3>
        <%= yield(:date) %></br>
      </h3>
      <table class="table is-striped">
        <thead>
          <tr>
            <th>Activity</th>
            <th>Type of calorie</th>
            <th>Time</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Activity</th>
            <th>Type of calorie</th>
            <th>Time</th>
            <th>Actions</th>
          </tr>
        </tfoot>
        <tbody class="calories">
          <%= render @calories %>
        </tbody>
        <%= paginate @calories %>
        <%= page_entries_info @calories %>
      </table>
    </div>
  </div>
</section>

app/views/calories/new.html.erb
<% provide(:title, 'New Register') %>
<% provide(:button_text, 'Create register') %>

<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= "Add a new register of calories" %>
      </h1>
      <h2 class="subtitle">
        <%= "#{current_user.email}" %>
      </h2>
      <h3>
        <%= yield(:date) %>
      </h3>
      <div class="columns">
        <div class="column is-two-fifths">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/calories/show.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= "Register of" %>
      </h1>
      <h2 class="subtitle">
        <%= "#{current_user.email}" %>
      </h2>
      <h3>
        <%= yield(:date) %>
      </h3>
      <table class="table is-striped">
        <thead>
          <tr>
            <th>Activity</th>
            <th>Type of calorie</th>
            <th>Time</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody class="calories">
          <%= render @calorie %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/calories/track.html.erb
<% provide(:title, "Tracking progress") %>

<section class="hero">
  <div class="hero-body">
    <div class="container">
      
      <div class="columns">
        <div class="column is-three-quarters">
          <h1 class="title">
            Track my progress
          </h1>
          <%= content_tag :div, "", id: "calories_chart", data: {calories: calories_chart_data} %>
        </div>
        <div class="column is-one-quarter">
          <h1 class="title">
            My goal
          </h1>
          <div class="field is-horizontal">
            <div class="field-label is-normal">
              <label class="label">Actual</label>
            </div>
            <div class="field-body">
              <div class="field">
                <div class="control">
                  <div class="notification is-rounded is-<%= message_type = ('danger' if calories_chart_data.last[:burned_number] - calories_chart_data.last[:gained_number] < 0) || 'success' %>" >
                    <%= calories_chart_data.last[:burned_number] - calories_chart_data.last[:gained_number] %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="field is-horizontal">
            <div class="field-label is-normal">
              <label class="label">Goal</label>
            </div>
            <div class="field-body">
              <div class="field">
                <div class="control">
                  <div class="notification is-rounded" type="text" placeholder="0">
                    <%= current_user.goal %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="field is-horizontal">
            <div class="field-body">
              <div class="field">
                <div class="control">
                  <div class="notification is-rounded is-<%= message_type = ('danger' if current_user.goal - (calories_chart_data.last[:burned_number] - calories_chart_data.last[:gained_number]) < 0) || ('warning' if current_user.goal - (calories_chart_data.last[:burned_number] - calories_chart_data.last[:gained_number]) > 0) || 'success' %>">
                    <% if current_user.goal - (calories_chart_data.last[:burned_number] - calories_chart_data.last[:gained_number]) < 0 %>
                      <%= "You have burned more calories than expected, please gain #{number_with_precision((current_user.goal - (calories_chart_data.last[:burned_number] - calories_chart_data.last[:gained_number])).abs, precision: 2)} calories." %>
                    <% elsif current_user.goal - (calories_chart_data.last[:burned_number] - calories_chart_data.last[:gained_number]) > 0 %>
                      <%= "C'mon mate, you can burne #{number_with_precision((current_user.goal - (calories_chart_data.last[:burned_number] - calories_chart_data.last[:gained_number])).abs, precision: 2)} more calories!" %>
                    <% else %>
                      <%= "Unitl now, you have achieved your daily goal, keep doing it." %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="columns">
        <div class="column is-one-quarter">
          <%= form_for(:track_reset, url: track_resets_path) do |f| %>
            <div class="field">
              <%= f.label :email, 'Share your progress', class: 'label' %>
              <div class="control">
                <%= f.email_field :email, type: 'email', class: 'input', placeholder: 'Add a valid email', required: true %>
              </div>
            </div>
            <%= f.submit "Submit", class: "button is-link" %>
          <% end %>
        </div>
        <div class="column is-one-fifth">
          <%= form_for(:goal_track_reset, url: goal_path) do |f| %>
            <div class="field">
              <%= f.label :goal, 'Update your daily goal', class: 'label' %>
              <div class="control">
                <%= f.number_field :number, class: 'input', step: 0.01, placeholder: 'Goal of the day', required: true %>
              </div>
            </div>
            <%= f.submit "Update", class: "button is-warning" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
  new Morris.Line({
    element: 'calories_chart',
    data: $('#calories_chart').data('calories'),
    xkey: 'date',
    ykeys: ['gained_number', 'burned_number'],
    labels: ['Gained calories', 'Burned calories'],
    hideHover: 'auto'
  });
</script>