config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
  get 'users/sign_out', to: 'users/sessions#destroy'
  end
  resources :calories
  get '/track', to: 'calories#track'
  resources :track_resets, only: [ :create ]
  get '/shared', to: 'track_resets#shared_progress'
  post '/goal', to: 'track_resets#update_goal'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Trafical</strong> as a result of a problem in <a href="https://www.hogaru.com/">Bootcamp - Hogaru</a>.
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">
      <img src="<%= asset_path('TRAFICAL.png') %>" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarTrafical">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarTrafical" class="navbar-menu">
    <div class="navbar-start">
      <a>
        <%= link_to "Home", root_path, class: "navbar-item"  %>
      </a>
      <% if user_signed_in? %>
        <a>
          <%= link_to "Register calories", new_calorie_path, class: "navbar-item"  %>
        </a>
        <a>
          <%= link_to "Registers", calories_path, class: "navbar-item"  %>
        </a>
      <% end %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
          <a>
            <%= link_to "Track my progress", track_path, class: "button is-light"  %>
          </a>
          <a>
            <%= link_to "Edit profile", edit_user_registration_path, class: "button is-light"  %>
          </a>
          <a>
            <%= link_to raw("<strong>Logout</strong>"), destroy_user_session_path, method: :delete, class: "button is-light"  %>
          </a>
          <% else %>
          <a>
            <%= link_to raw("<strong>Sign up</strong>"), new_user_registration_path, class: "button is-primary"  %>
          </a>
          <a>
            <%= link_to "Login", new_user_session_path, class: "button is-light"  %>
          </a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="columns">
        <div class="column is-half">
<!--           <div  id="error_explanation" class="notification is-#{message_type}"> -->
          <div  id="error_explanation" class="notification is-<%= message_type = ('danger' if message_type == 'alert') || message_type %>">
            <button class="delete" aria-label="delete"></button>
            <%= content_tag(:p, message) %>
          </div>
        </div>
      </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>